# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import jsonfield.fields
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('address1', models.CharField(max_length=256)),
                ('address2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=256)),
                ('country_name', models.CharField(max_length=256)),
                ('default', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('province', models.CharField(max_length=32, null=True)),
                ('province_code', models.CharField(max_length=32, null=True)),
                ('zip', models.CharField(max_length=16, null=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CarrierService',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('active', models.BooleanField(default=True)),
                ('callback_url', models.URLField()),
                ('carrier_service_type', models.CharField(default=b'api', max_length=16, choices=[(b'api', b'API'), (b'legacy', b'Legacy')])),
                ('format', models.CharField(default=b'json', max_length=8, choices=[(b'json', b'JSON'), (b'xml', b'XML')])),
                ('name', models.CharField(max_length=255)),
                ('service_discovery', models.BooleanField(default=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('collection_id', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('position', models.IntegerField(null=True)),
                ('product_id', models.IntegerField()),
                ('sort_value', models.CharField(max_length=16, null=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CustomCollection',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('body_html', models.TextField(null=True)),
                ('handle', models.CharField(max_length=255)),
                ('image', jsonfield.fields.JSONField(null=True)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('published_scope', models.CharField(default=b'global', max_length=16)),
                ('sort_order', models.CharField(max_length=16)),
                ('template_suffix', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=75)),
                ('first_name', models.CharField(max_length=64)),
                ('multipass_identified', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('last_order_id', models.IntegerField(null=True)),
                ('last_order_name', models.CharField(max_length=32, null=True)),
                ('note', models.TextField(null=True)),
                ('orders_count', models.IntegerField()),
                ('state', models.CharField(max_length=32)),
                ('tags', models.TextField()),
                ('total_spent', models.DecimalField(max_digits=10, decimal_places=2)),
                ('verified_email', models.BooleanField(default=False)),
                ('default_address', models.ForeignKey(related_name='default_address', to='shopify_sync.Address', null=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('position', models.IntegerField(default=1)),
                ('src', models.URLField()),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fulfillable_quantity', models.IntegerField()),
                ('fulfillment_service', models.CharField(max_length=32)),
                ('fulfillment_status', models.CharField(max_length=32, null=True)),
                ('grams', models.DecimalField(max_digits=10, decimal_places=2)),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('quantity', models.IntegerField()),
                ('requires_shipping', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('variant_title', models.CharField(max_length=256)),
                ('vendor', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('gift_card', models.BooleanField(default=False)),
                ('taxable', models.BooleanField(default=False)),
                ('tax_lines', jsonfield.fields.JSONField(default=[])),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Metafield',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=30)),
                ('namespace', models.CharField(max_length=20)),
                ('owner_id', models.IntegerField()),
                ('owner_resource', models.CharField(default=b'shop', max_length=32, choices=[(b'shop', b'Shop'), (b'product', b'Product')])),
                ('value', models.TextField()),
                ('value_type', models.CharField(default=b'string', max_length=32, choices=[(b'string', b'String'), (b'integer', b'Integer')])),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('billing_address', jsonfield.fields.JSONField()),
                ('browser_ip', models.IPAddressField(null=True)),
                ('buyer_accepts_marketing', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(max_length=32, null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('cart_token', models.CharField(max_length=32, null=True)),
                ('client_details', jsonfield.fields.JSONField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('currency', models.CharField(max_length=3)),
                ('discount_codes', jsonfield.fields.JSONField(default=[])),
                ('email', models.EmailField(max_length=75)),
                ('financial_status', models.CharField(max_length=32)),
                ('fulfillment_status', models.CharField(max_length=32, null=True)),
                ('tags', models.TextField()),
                ('landing_site', models.URLField(null=True)),
                ('name', models.CharField(max_length=32)),
                ('note', models.TextField()),
                ('note_attributes', jsonfield.fields.JSONField()),
                ('number', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('processed_at', models.DateTimeField()),
                ('processing_method', models.CharField(max_length=32)),
                ('referring_site', models.URLField(null=True)),
                ('shipping_address', jsonfield.fields.JSONField(null=True)),
                ('shipping_lines', jsonfield.fields.JSONField(default=[])),
                ('source_name', models.CharField(max_length=32)),
                ('tax_lines', jsonfield.fields.JSONField(default=[])),
                ('taxes_included', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=32)),
                ('total_discounts', models.DecimalField(max_digits=10, decimal_places=2)),
                ('total_line_items_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('total_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('total_tax', models.DecimalField(max_digits=10, decimal_places=2)),
                ('total_weight', models.DecimalField(max_digits=10, decimal_places=2)),
                ('customer', models.ForeignKey(to='shopify_sync.Customer')),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('body_html', models.TextField()),
                ('handle', models.CharField(max_length=255, db_index=True)),
                ('product_type', models.CharField(max_length=255, db_index=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('published_scope', models.CharField(default=b'global', max_length=64)),
                ('tags', models.CharField(max_length=255, blank=True)),
                ('template_suffix', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, db_index=True)),
                ('vendor', models.CharField(max_length=255, db_index=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ScriptTag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('event', models.CharField(max_length=16)),
                ('src', models.URLField()),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('myshopify_domain', models.CharField(unique=True, max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('shop_owner', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('customer_email', models.EmailField(max_length=75, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=16, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('province_code', models.CharField(max_length=32, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('country_code', models.CharField(max_length=32, null=True)),
                ('country_name', models.CharField(max_length=255, null=True)),
                ('latitude', models.DecimalField(null=True, max_digits=7, decimal_places=4)),
                ('longitude', models.DecimalField(null=True, max_digits=7, decimal_places=4)),
                ('timezone', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=4, null=True)),
                ('money_format', models.CharField(max_length=32, null=True)),
                ('money_in_emails_format', models.CharField(max_length=32, null=True)),
                ('money_with_currency_format', models.CharField(max_length=32, null=True)),
                ('money_with_currency_in_emails_format', models.CharField(max_length=32, null=True)),
                ('county_taxes', models.NullBooleanField(default=False)),
                ('tax_shipping', models.NullBooleanField(default=False)),
                ('taxes_included', models.NullBooleanField(default=False)),
                ('google_apps_domain', models.CharField(max_length=255, null=True)),
                ('google_apps_login_enabled', models.NullBooleanField(default=False)),
                ('plan_name', models.CharField(max_length=32, null=True)),
                ('plan_display_name', models.CharField(max_length=32, null=True)),
                ('password_enabled', models.NullBooleanField(default=False)),
                ('primary_location_id', models.IntegerField(null=True)),
                ('public', models.NullBooleanField(default=True)),
                ('eligible_for_payments', models.NullBooleanField(default=True)),
                ('requires_extra_payments_agreement', models.NullBooleanField(default=True)),
                ('source', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('body_html', models.TextField(null=True)),
                ('handle', models.CharField(max_length=255)),
                ('image', jsonfield.fields.JSONField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('published_scope', models.CharField(default=b'global', max_length=16)),
                ('rules', jsonfield.fields.JSONField()),
                ('disjunctive', models.BooleanField(default=False)),
                ('sort_order', models.CharField(max_length=16)),
                ('template_suffix', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('compare_at_price', models.DecimalField(null=True, max_digits=10, decimal_places=2)),
                ('fulfillment_service', models.CharField(default=b'manual', max_length=32)),
                ('grams', models.IntegerField()),
                ('inventory_management', models.CharField(default=b'blank', max_length=32, null=True)),
                ('inventory_policy', models.CharField(default=b'deny', max_length=32, null=True)),
                ('inventory_quantity', models.IntegerField()),
                ('option1', models.CharField(max_length=255, null=True)),
                ('option2', models.CharField(max_length=255, null=True)),
                ('option3', models.CharField(max_length=255, null=True)),
                ('position', models.IntegerField(default=1)),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=255, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('product', models.ForeignKey(to='shopify_sync.Product')),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('topic', models.CharField(max_length=64)),
                ('address', models.URLField()),
                ('format', models.CharField(max_length=4)),
                ('fields', jsonfield.fields.JSONField(null=True)),
                ('metafield_namespaces', jsonfield.fields.JSONField(null=True)),
                ('user', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(to='shopify_sync.Product'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='option',
            name='user',
            field=models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(to='shopify_sync.Order'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(to='shopify_sync.Product'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='user',
            field=models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='variant',
            field=models.ForeignKey(to='shopify_sync.Variant'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(to='shopify_sync.Product'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
